# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-20.04

stages:
- stage: TerraformInit
  jobs:
  - job: Init
    steps:
    - checkout: self
    - script: terraform init
      displayName: 'Terraform Init'
    - script: terraform validate
      displayName: 'Terraform Validate'
