# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-20.04

variables:
  azureSubscription: 'devops-integration-with-varshit-subscription'
  # ARM_CLIENT_ID: $(clientId)
  # ARM_CLIENT_SECRET: $(clientSecret)
  # ARM_SUBSCRIPTION_ID: $(subscriptionId)
  # ARM_TENANT_ID: $(tenantId)

stages:
- stage: TerraformInit
  jobs:
  - job: Init
    steps:
    - checkout: self
    - script: |
        echo "Setting environment variables for Terraform..."
        env | grep ARM
        echo "Initializing Terraform..."
        terraform init
        terraform apply -auto-approve
      displayName: 'Terraform Apply'